# Generated by Django 2.1.4 on 2019-06-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='aggregation_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Article Type'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='article_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Submission Type'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='arxiv_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ArXiv ID'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='eid',
            field=models.CharField(blank=True, max_length=200, verbose_name='EID'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='issn',
            field=models.CharField(blank=True, max_length=200, verbose_name='ISSN'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pubmed_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='PubMed ID'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='ss_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Semantic Scholar Paper ID'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='volume',
            field=models.CharField(blank=True, max_length=200, verbose_name='Volume'),
        ),
    ]
