# Generated by Django 2.2.2 on 2019-06-27 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_collection', '0002_auto_20190622_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('badge_class', models.CharField(choices=[('badge-primary', '<span class="badge badge-pill badge-primary">Resource Tag</span>'), ('badge-secondary', '<span class="badge badge-pill badge-secondary">Resource Tag</span>'), ('badge-success', '<span class="badge badge-pill badge-success">Resource Tag</span>'), ('badge-danger', '<span class="badge badge-pill badge-danger">Resource Tag</span>'), ('badge-warning', '<span class="badge badge-pill badge-warning">Resource Tag</span>'), ('badge-info', '<span class="badge badge-pill badge-info">Resource Tag</span>'), ('badge-light', '<span class="badge badge-pill badge-light">Resource Tag</span>'), ('badge-dark', '<span class="badge badge-pill badge-dark">Resource Tag</span>'), ('pink', '<span class="badge badge-pill pink">Resource Tag</span>'), ('indigo', '<span class="badge badge-pill indigo">Resource Tag</span>'), ('purple', '<span class="badge badge-pill purple">Resource Tag</span>'), ('orange', '<span class="badge badge-pill orange">Resource Tag</span>'), ('green', '<span class="badge badge-pill green">Resource Tag</span>'), ('blue-twitter', '<span class="badge badge-pill blue-twitter">Resource Tag</span>')], default='', max_length=20, verbose_name='Badge')),
                ('name', models.CharField(help_text='Note: The name of the Topic will be saved as lowercase to simplify research', max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='ai_collection.Topic', verbose_name='Topic'),
        ),
    ]
