# Generated by Django 2.2.2 on 2019-07-03 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_collection', '0003_auto_20190627_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='pathology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='ai_collection.Pathology', verbose_name='Pathology'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='ai_collection.Topic', verbose_name='Topic'),
        ),
    ]
