# Generated by Django 2.2.2 on 2019-07-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_collection', '0004_auto_20190703_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Azure Keyphrases')),
            ],
            options={
                'verbose_name': 'Azure Keyphrase',
                'verbose_name_plural': 'Azure Keyphrases',
                'ordering': ['name'],
            },
        ),
    ]
