# Generated by Django 2.2.2 on 2019-07-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_collection', '0006_paper_azure_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurekey',
            name='badge_class',
            field=models.CharField(choices=[('badge-primary', '<span class="badge badge-pill badge-primary">Resource Tag</span>'), ('badge-secondary', '<span class="badge badge-pill badge-secondary">Resource Tag</span>'), ('badge-success', '<span class="badge badge-pill badge-success">Resource Tag</span>'), ('badge-danger', '<span class="badge badge-pill badge-danger">Resource Tag</span>'), ('badge-warning', '<span class="badge badge-pill badge-warning">Resource Tag</span>'), ('badge-info', '<span class="badge badge-pill badge-info">Resource Tag</span>'), ('badge-light', '<span class="badge badge-pill badge-light">Resource Tag</span>'), ('badge-dark', '<span class="badge badge-pill badge-dark">Resource Tag</span>'), ('pink', '<span class="badge badge-pill pink">Resource Tag</span>'), ('indigo', '<span class="badge badge-pill indigo">Resource Tag</span>'), ('purple', '<span class="badge badge-pill purple">Resource Tag</span>'), ('orange', '<span class="badge badge-pill orange">Resource Tag</span>'), ('green', '<span class="badge badge-pill green">Resource Tag</span>'), ('blue-twitter', '<span class="badge badge-pill blue-twitter">Resource Tag</span>')], default='', max_length=20, verbose_name='Badge'),
        ),
    ]
