# Generated by Django 2.2.2 on 2019-07-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_collection', '0007_azurekey_badge_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azurekey',
            name='badge_class',
        ),
    ]
