# Generated by Django 2.2.2 on 2019-07-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_collection', '0008_remove_azurekey_badge_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='update_azure_keys',
            field=models.BooleanField(default=True, verbose_name='Update Azure keys'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='azure_keys',
            field=models.ManyToManyField(blank=True, related_name='papers', to='ai_collection.AzureKey', verbose_name='Azure Keys'),
        ),
    ]
