# Generated by Django 2.2.2 on 2019-07-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_collection', '0009_auto_20190704_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='azure_keys',
            field=models.ManyToManyField(blank=True, related_name='datasets', to='ai_collection.AzureKey', verbose_name='Azure Keys'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='update_azure_keys',
            field=models.BooleanField(default=True, verbose_name='Update Azure keys'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='publication_date',
            field=models.DateField(verbose_name='Publication Date'),
        ),
    ]
