# Generated by Django 2.2.2 on 2019-07-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_collection', '0010_auto_20190704_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Publication Date'),
        ),
    ]
